Armazon_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls", namespace="store")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
   path('register', views.user_register, name="user_register"),
   path('login', views.user_login, name="user_login"),
   path('logout', views.user_logout, name="user_logout"), 
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path('', views.home, name="home"),
    path('category/<str:category_title>', views.category_product, name="category"),
    path('product/info/<int:product_id>', views.product_info, name="product_info"),
    path('cart/add/<int:product_id>', views.add_cart, name="add_card"),
    path('cart/info/<int:user_id>', views.cart_info, name="cart_info"),
    path('comment/add/<int:product_id>', views.add_comment, name="add_comment"),
    path('comment/delete/<int:product_id>', views.delete_comment, name="comment_delete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField

class CustomerAccount(AbstractUser):
    username = PhoneNumberField(region="IR", unique=True)

    USERNAME_FIELD = 'username'

    def __str__(self):
        return f'{self.first_name} - {self.last_name}'  

store/models.py
from django.db import models
from accounts.models import CustomerAccount
from phonenumber_field.modelfields import PhoneNumberField

class Category(models.Model):
    name = models.CharField(max_length=300, unique=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200 ,null=False ,blank=False)
    brand = models.CharField(max_length=100)
    category = models.ForeignKey(Category ,on_delete=models.CASCADE)
    price = models.IntegerField(null=False ,blank=False)
    image = models.ImageField(null=True ,blank=True)
    description = models.TextField(max_length=200)
    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.ForeignKey(CustomerAccount, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantities = models.PositiveSmallIntegerField()

class Comment(models.Model):
    user = models.ForeignKey(CustomerAccount, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    body = models.TextField()
    SCORE = (
          ("0%", "0%"),
          ("10%", "10%"),
          ("20%", "20%"),
          ("30%", "30%"),
          ("40%", "40%"),
          ("50%", "50%"),
          ("60%", "60%"),
          ("70%", "70%"),
          ("80%", "80%"),
          ("90%", "90%"),
          ("100%", "100%"),
	)
    score = models.CharField(max_length=5)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
    	return f'{self.user} - {self.body[:30]} - {self.product}'

accounts/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField

class UserRegisterForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = PhoneNumberField(region="IR", label="Phone Number")
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserLoginForm(forms.Form):
    username = PhoneNumberField(region="IR")
    password = forms.CharField(widget=forms.PasswordInput)

store/forms.py
from django import forms
from django.forms import Select
from .models import Cart, Comment

class AddCartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ("quantities",)

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body", "score")
        widgets = {
            'score' : forms.TextInput(attrs={"placeholder" : "0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%"}),
        }   

accounts/views.py
from django.shortcuts import render, redirect
from .models import CustomerAccount
from .forms import UserRegisterForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def user_register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = CustomerAccount.objects.create_user(cd["username"], cd["email"], cd["password"])
            user.first_name = cd["first_name"]
            user.last_name = cd["last_name"]
            user.save()
            messages.success(request, "Registered Successfully", 'success')
            return redirect("accounts:user_login")
    else:
        form = UserRegisterForm()
    return render(request, "accounts/register.html", {"form" : form})

def user_login(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username = cd["username"], password = cd["password"])
            if user is not None:
                login(request, user)
                messages.success(request, "Logged in Successfully", 'success')
                return redirect("store:home")
            else:
                messages.error(request, "Phone Number or Password is wrong", 'danger')
                return redirect("accounts:user_login")
    else:
        form = UserLoginForm()
    return render(request, "accounts/login.html", {"form" : form})

@login_required(login_url="accounts:user_login")
def user_logout(request):
    logout(request)
    messages.success(request, "Logged out Successfully", 'success')
    return redirect("store:home")

store/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import AddCartForm, AddCommentForm
from .models import Category, Product, Comment, Cart

def home(request):
    category = Category.objects.all()
    return render(request, "store/index.html", {"categories" : category})

def category_product(request, category_title):
    products = Product.objects.filter(category__name=category_title)
    return render(request, "store/category_products.html", {"products" : products})

def product_info(request, product_id):
    products = Product.objects.filter(id=product_id)
    for product in products:
        image = product.image.name
    comments = Comment.objects.filter(product__id=product_id)
    return render(request, "store/product_info.html", {"products" : products, "image" : image, "comments" : comments})

@login_required(login_url="accounts:user_login")
def add_cart(request, product_id):
    if request.method == "POST":
        form = AddCartForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            product = Product.objects.filter(id=product_id)
            cart = form.save(commit=False)
            cart.product = product.first()
            cart.user = request.user
            cart.save()
            messages.success(request, "Product added to cart successfully", 'success')
            return redirect("store:home")
    else:
        form = AddCartForm()
    return render(request, "store/add_cart.html", {"form" : form})

@login_required(login_url="accounts:user_login")
def cart_info(request, user_id):
    cart = Cart.objects.filter(user__id=user_id)
    return render(request, "store/cart_info.html", {"carts" : cart})

@login_required(login_url="accounts:user_login")
def add_comment(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == "POST":
        form = AddCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.product = product
            comment.save()
            messages.success(request, "Comment added successfully", 'success')
            return redirect("store:product_info", product_id)
    else:
        form = AddCommentForm()
    return render(request, "store/add_comment.html", {"form" : form})

@login_required(login_url="accounts:user_login")
def delete_comment(request, product_id):
    comment = Comment.objects.filter(product__id=product_id).delete()
    messages.success(request, "Comment Deleted Successfully", 'success')
    return redirect("store:product_info", product_id)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}<title>Login Page | Armazon Shop</title>{% endblock %}

{% block content %}
<h1>Login Form</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login" class="btn btn-outline-primary">
</form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}<title>Register Page | Armazon Shop</title>{% endblock %}

{% block content %}
<h1>Register Form</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register" class="btn btn-outline-primary">
</form>
{% endblock %}

store/templates/store/add_cart.html
{% extends 'base.html' %}

{% block title %}<title>Adding to card | Armazon Shop</title>{% endblock %}

{% block content %}
<h1>Qantity of product form</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Add" class="btn btn-outline-primary">
</form>
{% endblock %}

store/templates/store/add_comment.html
{% extends 'base.html' %}

{% block title %}<title>Comment Add | Armazon Shop</title>{% endblock %}

{% block content %}
<h1>Comment add Form</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Add" class="btn btn-outline-primary">
</form>
{% endblock %}

store/templates/store/cart_info.html
{% extends 'base.html' %}

{% block title %}<title>Cart Info | Armazon Shop</title>{% endblock %}

{% block content %}
<h1>Your Cart</h1><hr />
<h3>The number of products which are in your cart is <span style="color : red">{{carts.count}}</span></h3>
{% for cart in carts %}
    <h3>{{forloop.counter}}. {{cart.product}} - quantity : {{cart.quantities}}</h3>
{% endfor %}
{% endblock %}

store/templates/store/category_products.html
{% extends 'base.html' %}

{% block title %}<title>Category products | Armazon Shop</title>{% endblock %}


{% block content %}
{% for product in products %}
<h1>{{product.name}}</h1>
<a href="{% url 'store:product_info' product.id %}" class="btn btn-outline-info">Info</a>
{% endfor %}
{% endblock %}

store/templates/store/index.html
{% extends 'base.html' %}

{% block title %}<title>Home Page | Armazon Shop</title>{% endblock %}

{% block content %}

    {% for category in categories %}
    <a href="{% url 'store:category' category.name %}" style="text-decoration: none;"><h1 style="text-align: center;">{{category.name}}</h1></a><hr />
    {% endfor %}
<hr />

<h1>Your cart</h1>
{% if request.user.is_authenticated %}
<a href="{% url 'store:cart_info' request.user.id %}" class="btn btn-outline-info">Your Cart</a>
{% else %}
<h1 class="alert alert-warning">You have to login in order to see your cart</h1>
{% endif %}
{% endblock %}

store/templates/store/product_info.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Product info | Armazon Shop</title>{% endblock %}

{% block content %}
{% for product in products %}
    <h1>{{product.name}}</h1><hr />
    <img src="{% static image %}" alt="Picture of Product"><hr />
    <h5>{{product.description}}</h5><hr />
    <h3>Price:${{product.price}}</h3>
    <a href="{% url 'store:add_card' product.id %}" class="btn btn-outline-success">Add to card</a>
<hr /><br />
<h1>Comments</h1>
{% if request.user.is_authenticated %}
<a href="{% url 'store:add_comment' product.id  %}" class="btn btn-outline-secondary">Add Comment</a><hr />
{% else %}
<h2 class="alert alert-warning">For adding comments you must login</h2>
{% endif %}
{% for comment in comments %}
<b><h3>User : {{comment.user.first_name}}-{{comment.user.last_name}}</h3></b><br />
<h2>{{comment.body}}</h2>
<h3>Score : {{comment.score}}</h3>
{% if comment.user == request.user %}
<a href="{% url 'store:comment_delete' product.id %}" class="btn btn-outline-danger">Delete Comment</a>
{% endif %}
<hr />
{% endfor %}
{% endfor %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Page</title>{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
        .jumbotron{
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
        hr{
            color:darkcyan
        }
        img{
            height: 200px;
            width: 200px;
        }    
    </style>
</head>
<body>

    {% include 'includes/navbar.html' %}
    <div class="jumbotron">
        {% include 'includes/messages.html' %}
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>

templates/includes/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'store:home' %}">Armazon Shop</a>
      {% if request.user.is_authenticated %}
      <a class="btn btn-outline-danger" href="{% url 'accounts:user_logout' %}" style="color:white">logout</a>
      {% else %}
      <a class="btn btn-outline-info" href="{% url 'accounts:user_register' %}" style="margin-right: 10px;margin-right: 1500px;color: white;">register</a>
      <a class="btn btn-outline-primary" href="{% url 'accounts:user_login' %}" style="float: left;color:white;">login</a>
      {% endif %}
  </div>
</nav>